package pacote_12643.visao;

import java.awt.event.ActionEvent;
import java.util.HashMap;

import javax.swing.JOptionPane;

import pacote_12643.modelo.Parametrizacao;

/**
 * Diálogo de uma nova parametrização.
 * @author Tiago
 */
/**
 * @author Tiago
 *
 */
@SuppressWarnings("serial")
public class DialogoParametrizacao extends javax.swing.JDialog {
	/**
	 * Parametrização criada.
	 */
	private Parametrizacao parametrizacao;
	/**
	 * Tabela de opções para número de bolas.
	 */
	private HashMap<String, Integer> tabelaBolas;
	/**
	 * Tabela de opções para nível de dificuldade.
	 */
	private HashMap<String, Parametrizacao.Nivel> tabelaNiveis;

	/**
	 * Construtor
	 * @param parent
	 */
	public DialogoParametrizacao(java.awt.Frame parent) {
		super(parent, true);
		initComponents();

		// Instancia tabelas
		tabelaBolas = new HashMap<String, Integer>();
		tabelaBolas.put((String) jComboBoxBolas.getItemAt(0), 2);
		tabelaBolas.put((String) jComboBoxBolas.getItemAt(1), 3);
		tabelaBolas.put((String) jComboBoxBolas.getItemAt(2), 4);

		tabelaNiveis = new HashMap<String, Parametrizacao.Nivel>();
		tabelaNiveis.put((String) jComboBoxNivel.getItemAt(0),
				Parametrizacao.Nivel.FACIL);
		tabelaNiveis.put((String) jComboBoxNivel.getItemAt(1),
				Parametrizacao.Nivel.MEDIO);
		tabelaNiveis.put((String) jComboBoxNivel.getItemAt(2),
				Parametrizacao.Nivel.DIFICIL);
		
		jComboBoxBolas.setSelectedIndex(1);
		jComboBoxNivel.setSelectedIndex(1);

		setVisible(true);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc=" Generated Code ">
	private void initComponents() {
		java.awt.GridBagConstraints gridBagConstraints;

		jPanelDados = new javax.swing.JPanel();
		jLabelNome = new javax.swing.JLabel();
		jTextFieldNome = new javax.swing.JTextField();
		jLabelBolas = new javax.swing.JLabel();
		jComboBoxBolas = new javax.swing.JComboBox();
		jLabelNivel = new javax.swing.JLabel();
		jComboBoxNivel = new javax.swing.JComboBox();
		jPanelBotoes = new javax.swing.JPanel();
		jButtonIniciar = new javax.swing.JButton();
		jButtonCancelar = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Novo Jogo");
		setModal(true);
		jPanelDados.setLayout(new java.awt.GridBagLayout());

		jLabelNome.setText("Nome:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
		gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
		jPanelDados.add(jLabelNome, gridBagConstraints);

		jTextFieldNome.setColumns(10);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
		jPanelDados.add(jTextFieldNome, gridBagConstraints);

		jLabelBolas.setText("Bolas:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridy = 2;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
		gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
		jPanelDados.add(jLabelBolas, gridBagConstraints);

		jComboBoxBolas.setModel(new javax.swing.DefaultComboBoxModel(
				new String[] { "2", "3", "4" }));
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridy = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
		jPanelDados.add(jComboBoxBolas, gridBagConstraints);

		jLabelNivel.setText("N\u00edvel:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridy = 3;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
		gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
		jPanelDados.add(jLabelNivel, gridBagConstraints);

		jComboBoxNivel.setModel(new javax.swing.DefaultComboBoxModel(
				new String[] { "F\u00e1cil", "M\u00e9dio", "Dificil" }));
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridy = 3;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
		jPanelDados.add(jComboBoxNivel, gridBagConstraints);

		getContentPane().add(jPanelDados, java.awt.BorderLayout.CENTER);

		jButtonIniciar.setText("Iniciar");
		jButtonIniciar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonIniciarActionPerformed(evt);
			}
		});

		jPanelBotoes.add(jButtonIniciar);

		jButtonCancelar.setText("Cancelar");
		jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonCancelarActionPerformed(evt);
			}
		});

		jPanelBotoes.add(jButtonCancelar);

		getContentPane().add(jPanelBotoes, java.awt.BorderLayout.SOUTH);

		java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit()
				.getScreenSize();
		setBounds((screenSize.width - 250) / 2, (screenSize.height - 180) / 2,
				250, 180);
	}// </editor-fold>//GEN-END:initComponents

	private void jButtonCancelarActionPerformed(ActionEvent evt) {
		dispose();
	}

	//GEN-FIRST:event_jButtonIniciarActionPerformed
	private void jButtonIniciarActionPerformed(java.awt.event.ActionEvent evt) {
		// Validação
		String nomeJogador = jTextFieldNome.getText().trim();
		
		if (nomeJogador.length() == 0) {
			JOptionPane.showMessageDialog(this, "Entre com um nome para o jogador!", "Erro", JOptionPane.ERROR_MESSAGE);
			return;
		}
		
		int numeroBolas = tabelaBolas.get(jComboBoxBolas.getSelectedItem());
		Parametrizacao.Nivel nivel = tabelaNiveis.get(jComboBoxNivel
				.getSelectedItem());

		// Cria nova parametrização.
		parametrizacao = new Parametrizacao(nomeJogador, numeroBolas, nivel, false);

		dispose();
	}//GEN-LAST:event_jButtonIniciarActionPerformed

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButtonCancelar;
	private javax.swing.JButton jButtonIniciar;
	private javax.swing.JComboBox jComboBoxBolas;
	private javax.swing.JComboBox jComboBoxNivel;
	private javax.swing.JLabel jLabelBolas;
	private javax.swing.JLabel jLabelNivel;
	private javax.swing.JLabel jLabelNome;
	private javax.swing.JPanel jPanelBotoes;
	private javax.swing.JPanel jPanelDados;
	private javax.swing.JTextField jTextFieldNome;
	// End of variables declaration//GEN-END:variables

	public Parametrizacao getParametrizacao() {
		return parametrizacao;
	}

}