package pacote_12643.visao;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

/**
 * Janela principal do jogo.
 * @author Tiago
 */
@SuppressWarnings("serial")
public class JanelaPrincipal extends javax.swing.JFrame {

	/**
	 * Construtor
	 */
	public JanelaPrincipal() {
		initComponents();
		new MediatorPrincipal(this);
		
		setResizable(false);
		setTitle("Snookin' Down!");
		
		// Eventos
		this.addWindowListener(new WindowAdapter(){
			public void windowClosed(WindowEvent arg0) {
				jPanelJogo.sair();
			}
		});
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc=" Generated Code ">
	private void initComponents() {
		jPanelJogo = new PanelTabuleiro(this);
		jPanelStatus = new PanelPlacar();
		jMenuBar = new javax.swing.JMenuBar();
		jMenuJogo = new javax.swing.JMenu();
		jMenuItemNovoJogo = new javax.swing.JMenuItem();
		jMenuItemDemo = new javax.swing.JMenuItem();
		jMenuItemVisualizarRanking = new javax.swing.JMenuItem();
		jSeparator = new javax.swing.JSeparator();
		jMenuItemSair = new javax.swing.JMenuItem();
		jMenuAjuda = new javax.swing.JMenu();
		jMenuItemAjuda = new javax.swing.JMenuItem();
		jMenuItemSobre = new javax.swing.JMenuItem();
		jMenuItemTerminar = new javax.swing.JMenuItem();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		getContentPane().add(jPanelJogo, java.awt.BorderLayout.CENTER);
		getContentPane().add(jPanelStatus, java.awt.BorderLayout.SOUTH);

		jMenuJogo.setText("Jogo");
		jMenuItemNovoJogo.setText("Novo Jogo...");
		jMenuJogo.add(jMenuItemNovoJogo);
		
		jMenuItemTerminar.setText("Terminar Jogo");
		jMenuItemTerminar.setEnabled(false);
		jMenuJogo.add(jMenuItemTerminar);

		jMenuItemDemo.setText("Demonstra\u00e7\u00e3o");
		jMenuJogo.add(jMenuItemDemo);

		jMenuItemVisualizarRanking.setText("Visualizar ranking...");
		jMenuJogo.add(jMenuItemVisualizarRanking);

		jMenuJogo.add(jSeparator);

		jMenuItemSair.setText("Sair");
		jMenuJogo.add(jMenuItemSair);

		jMenuBar.add(jMenuJogo);

		jMenuAjuda.setText("Ajuda");
		jMenuItemAjuda.setText("Ajuda...");
		jMenuAjuda.add(jMenuItemAjuda);

		jMenuItemSobre.setText("Sobre...");
		jMenuAjuda.add(jMenuItemSobre);

		jMenuBar.add(jMenuAjuda);

		setJMenuBar(jMenuBar);

		java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit()
				.getScreenSize();
		setBounds((screenSize.width - 350) / 2, (screenSize.height - 680) / 2,
				350, 680);
	}// </editor-fold>//GEN-END:initComponents

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JMenu jMenuAjuda;
	private javax.swing.JMenuBar jMenuBar;
	private javax.swing.JMenuItem jMenuItemAjuda;
	private javax.swing.JMenuItem jMenuItemDemo;
	private javax.swing.JMenuItem jMenuItemNovoJogo;
	private javax.swing.JMenuItem jMenuItemSair;
	private javax.swing.JMenuItem jMenuItemSobre;
	private javax.swing.JMenuItem jMenuItemVisualizarRanking;
	private javax.swing.JMenuItem jMenuItemTerminar;
	private javax.swing.JMenu jMenuJogo;
	private PanelTabuleiro jPanelJogo;
	private PanelPlacar jPanelStatus;
	private javax.swing.JSeparator jSeparator;
	// End of variables declaration//GEN-END:variables
	
	// Métodos get
	public javax.swing.JMenuItem getJMenuItemAjuda() {
		return jMenuItemAjuda;
	}

	public javax.swing.JMenuItem getJMenuItemDemo() {
		return jMenuItemDemo;
	}

	public javax.swing.JMenuItem getJMenuItemNovoJogo() {
		return jMenuItemNovoJogo;
	}

	public javax.swing.JMenuItem getJMenuItemSair() {
		return jMenuItemSair;
	}

	public javax.swing.JMenuItem getJMenuItemSobre() {
		return jMenuItemSobre;
	}

	public javax.swing.JMenuItem getJMenuItemVisualizarRanking() {
		return jMenuItemVisualizarRanking;
	}

	public PanelTabuleiro getJPanelJogo() {
		return jPanelJogo;
	}

	public PanelPlacar getJPanelStatus() {
		return jPanelStatus;
	}
	
	public javax.swing.JMenuItem getJMenuItemTerminar() {
		return jMenuItemTerminar;
	}

	/**
	 * Trava menus para focar o jogo.
	 * @param travar
	 */
	public void travarMenus(boolean travar) {
		jMenuItemNovoJogo.setEnabled(!travar);
		jMenuItemDemo.setEnabled(!travar);
		jMenuItemVisualizarRanking.setEnabled(!travar);
		jMenuItemAjuda.setEnabled(!travar);
		jMenuItemSobre.setEnabled(!travar);
		jMenuItemTerminar.setEnabled(travar);
	}
	
}